---
title: "mywebsite"
author: "Sarah Power"
date: "November 29, 2017"
output: html_document
editor_options: 
  chunk_output_type: console
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

## R Markdown

Here we go again.

```{r, cache = TRUE}
escapement <- read.csv("ADFG_firstAttempt_reformatted.csv",  stringsAsFactors = FALSE)
```
```{r}
library(tidyr)
library(dplyr)
library(leaflet)
library(ggplot2)
library(DT)
```

```{r}
median_esc <- escapement %>% 
  separate(sampleDate, c("Year", "Month", "Day"), sep = "-") %>% 
  group_by(Species, Year, Location) %>% 
  summarize(escapement = sum(DailyCount, na.rm = TRUE)) %>% 
  group_by(Species) %>% 
  summarize(median_escapement = median(escapement))
```

```{r}
ggplot(median_esc, aes(Species, median_escapement)) +
  geom_col() +
  coord_flip()
```
```{r}
datatable(median_esc)
```

```{r}
locations <- escapement %>% 
  distinct(Location, Latitude, Longitude) %>% 
  drop_na()

datatable(locations)
```

```{r}
leaflet(locations) %>% 
  addTiles() %>% 
  addMarkers(~ -abs(Longitude), ~ Latitude, popup = ~ Location)
```

